name = "BioFlows"
uuid = "b64b6e3f-2b8e-4d14-86d2-6b8f5a3f1e40"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>", "Dibyendu Ghosh <dibyendughosh.iitkgp@gmail.com>"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PencilArrays = "0e08944d-e94e-41b1-9406-dcf66b6a9d2e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
PencilArrays = "0.19.7"
Statistics = "1.10, 1.11"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
